### ISSUE TITLE
B track  dataset name 을 알수 있을까요??

### ISSUE THREAD

**Issue by gywns6287** [Korea-Health-Datathon/KHD2020#20]
nsml run -d [데이터셋] 
에 입력해야하는 데이터셋의 name 을 알 수 있을까요

아니면 혹시 아직 데이터셋이 개제 되지 않은 건가요?
nsml dataset ls 로 확인해보면 
Name        Size    Last Modified    Author    Description    Tag    Authority
----------  ------  ---------------  --------  -------------  -----  -----------
hello       10 KB   10 months ago    nsmlteam                        public
hello_nsml  10 KB   10 months ago    nsmlteam                        public
nsml_test   18 B    10 days ago      nsmlteam                        public

결과만 확인이 되어 문의드립니다.

**Comment by philip555** [comment]
Breast_Pathology 입니다. 

감사합니다.

**Comment by rinha7** [comment]
permission denied 뜨는데, 수정 부탁드릴 수 있을까요?

**Comment by yharam00** [comment]
a track은 nsml run -d [데이터셋] 있는거 다 해봐도
Rejected: not enough credit (balance: 0)
Since cluster does not have enough computing resources, job has been aborted. Please retry later
Error: No machine available that meets ALL your request such as CPU, RAM, Disk, GPU or its driver version
time="2020/09/21 15:36:33.645" level=fatal msg="Internal server error"
밖에 안나옵니다..

**Comment by Korea-Health-Datathon** [comment]
추가 Credit 부여 및 데이터셋 Permission 수정 완료되었습니다.
